config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :users
  resources :stocks, only: [:new, :create, :show]
  resources :watchlists, only: [:index, :new, :create, :destroy]
  resources :portfolio

  get 'search_stocks', to: "stocks#search"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
  has_many :user_watchlists
  has_many :users, through: :user_watchlists

  # validate stock symbol and name are in the db and that only one instance is saved
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :ticker, presence: true

  # before saving uppercase all letters
  before_save :uppercase_field


  # return ticker symbol in our database instead of querying
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  # lookup ticker through stock quote
  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name

    new_watch = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_watch
  end

  # return current ask price of stock
  def self.price(ticker_symbol)
    StockQuote::Stock.quote(ticker_symbol).ask
  end

  # parse through array of watchlist objects returning ticker in new array
  def self.stock_tickers(watchlist_obj)
    watchlist_obj.map { |stock| stock.ticker }
  end

  private

    def uppercase_field
      self.ticker.upcase!
    end
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController

  def index
    @user_watchlist = current_user.watchlists
    @watchlist = Watchlist.stock_tickers(@user_watchlist).sort
    respond_to do |format|
      format.html { redirect_to portfolio_index_path }
      format.js
    end

  end

  def create
    user = current_user

    # check to see if stock is in db
    watch = Watchlist.find_by_ticker(watchlist_param[:ticker].upcase)
    if watch

      # check to see if user already has in portfolio
      if !stock_in_portfolio?(user, watch)
        @add_stock_watchlist = UserWatchlist.new(user_id: user.id, watchlist_id: watch.id)   # create new record in join table
        @add_stock_watchlist.save
      end

    else

      # if not check api to get values and then save stock
      watch = Watchlist.new_from_lookup(watchlist_param[:ticker])
      if watch
        watch.save

        # check to see if user already has in portfolio
        if !stock_in_portfolio?(user, watch)
          @add_stock_watchlist = UserWatchlist.new(user_id: user.id, watchlist_id: watch.id)   # create new record in join table
          @add_stock_watchlist.save
        end

      else
        # if not in api return back with error msg
        flash[:notice] = "Symbol was not found."
      end
    end

    respond_to do |format|
     format.html { redirect_to portfolio_index_path }
     format.js
    end
  end

  def destroy
    user_watchlist = UserWatchlist.where(user_id: current_user.id, watchlist_id: params[:id])
    @watch_id = user_watchlist.first.watchlist_id.to_s
    user_watchlist.first.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_index_path }
      format.js
    end
  end

  private

    def watchlist_param
      params.require(:watchlist).permit(:ticker)
    end

    def stock_in_portfolio?(user, watch)
      UserWatchlist.where(user_id: user.id, watchlist_id: watch.id).exists?
    end

end

app/views/watchlists/_stock_watchlist.html.erb
<% watch = Watchlist.find_by(ticker: stock.symbol.upcase) %>
<% if stock.change[0] == '-' %>
  <tr id="spy<%= watch.id %>" class="h5 cold">
<% else %>
  <tr id="spy<%= watch.id %>" class="h5 hot">
<% end %>
    <td><%= stock.symbol.upcase %></td>
    <td><%= get_market_price(stock) %></td>
    <td><%= stock.change %></td>
    <td>
      <%= link_to(" ", watchlist_path(watch), method: :delete,
                                                  class: "glyphicon glyphicon-remove", remote: true )%>
    </td>
  </tr>

app/views/watchlists/_watchlist.html.erb
<table id="watchlist" class="table-borderless table-condensed table-hover text-center">
  <tr class="h4">
    <th><strong>Ticker</strong></th>
    <th><strong>Price</strong></th>
    <th><strong>Change</strong></th>
    <th><%= link_to("", watchlists_path, id: "refresh-watch",
                                class: "navi-btn glyphicon glyphicon-refresh", remote: true) %>
  </tr>
  <% watchlist_data = stock_watchlist(watchlist) %>
  <% watchlist_data.each do |data| %>
    <%= render '/watchlists/stock_watchlist', stock: data %>
  <% end %>
</table>

app/views/watchlists/create.js.erb
<% new_stock_watch = stock_info( [Watchlist.find(@add_stock_watchlist.watchlist_id).ticker] ) %>
$('#watchlist tbody').append('<%= j render "/watchlists/stock_watchlist", stock: new_stock_watch.first %>');
$('#watchlist_ticker').val('')
                      .next()
                      .attr('disabled', true);

app/views/watchlists/destroy.js.erb
$('#spy<%= j @watch_id %>').remove();

app/views/watchlists/index.js.erb
$parent = $('#watchlist').parent();                    // grab parent to append to

$('#watchlist').remove();                              // remove contents
$parent.append( '<%= j render "watchlist", watchlist: @watchlist %>' );

$refresh = $('#refresh-watch');
$refresh.addClass('gly-spin').delay(1000).queue(function() {  // animation
  $refresh.removeClass('gly-spin');
  $refresh.dequeue();
}, 1000);