config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :users
  resources :stocks, only: [:new, :create, :show]
  resources :watchlists, only: [:index, :new, :create, :destroy]
  resources :portfolio

  get 'search_stocks', to: "stocks#search"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">

  <div id="foot-logo" class="col-xs-6 col-xs-offset-3">
    <%= image_tag "logo.png", alt: "logo"%>
  </div>

  <div class="col-xs-12">

    <p id="foot-info">THIS IS A DEMO <br/>
      APP CREATED BY <a href="http://pratikmshah.github.io/">PRATIK SHAH</a>
    </p>

    <ul id="social" class="list-unstyled list-inline">
      <li>
        <a href="https://github.com/pratikmshah"><%= image_tag "github.png", alt: "github", title: "github" %></a>

      </li>
      <li>
        <a href="https://twitter.com/pratikshah"><%= image_tag "twitter.png", alt: "twitter", title: "twitter" %></a>
      </li>
      <li>
        <a href="https://linkedin.com/in/pratikmshah"><%= image_tag "linkedin.png", alt: "linkedin", title: "linkedin" %></a>
      </li>
      <li>
        <a href="mailto:pratik.t.shah@gmail.com"><%= image_tag "email.png", alt: "email", title: "email" %></a>
      </li>
    </ul>

  </div>

</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid no-pad">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 col-xs-12">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a id="brand-logo" href="/"> <%= image_tag "logo.png", class: 'navbar-brand' %> </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul id="navbar-r" class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>

            <!-- add stock to portfolio -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle navi-btn" data-toggle="dropdown"
                                                      role="button" aria-haspopup="true" aria-expanded="false">
                                                      <span class="glyphicon glyphicon-cog"></span></a>
              <ul class="dropdown-menu">
                <% if flash[:hide_form] == false %>
                  <li>
                    <%= form_for(@stock, remote: true, html: { class: "navbar-form navbar-right no-marg", role: "add stock" }) do |f| %>
                      <div id="add-stock" class="form-group">
                        <%= f.text_field :ticker, placeholder: "Ticker, Symbol", class: "form-control", autocomplete: "off" %>
                        <%= f.submit "Add stock", class: "btn btn-success form-control" %>
                      </div>
                    <% end %>
                  </li>
                  <li role="separator" class="divider"></li>
                <% end %>
                <% if @portfolio %>
                  <li> <%= link_to(portfolio_index_path, id: "refresh",
                                                    class: "navi-btn", remote: true) do %>
                                                    <span class="glyphicon glyphicon-refresh"></span>
                                                    <span>Refresh</span>
                                                    <% end %></li>
                <% else %>
                  <li> <%= link_to(portfolio_path(params[:id]), id: "refresh",
                                                    class: "navi-btn") do %>
                                                    <span class="glyphicon glyphicon-refresh"></span>
                                                    <span>Refresh</span>
                                                    <% end %></li>
                <% end %>
               <li> <a href="#" title="Remove stock from portfolio", id="delete", class="navi-btn">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                    <span>Delete</span></a> </li>

               <li role="separator" class="divider"></li>
               <li> <%= link_to(destroy_user_session_path, method: :delete,
                                                    id: "logout", class: "navi-btn") do %>
                                                    <span class="glyphicon glyphicon-menu-right"></span>
                                                    <span>Logout</span>
                                                    <% end %></li>
             </ul>
            </li>

             <!-- watchlist -->
             <li class="dropdown">
              <a href="#" class="dropdown-toggle navi-btn" data-toggle="dropdown"
                                                      role="button" aria-haspopup="true" aria-expanded="false">
                                                      <span class="glyphicon glyphicon-eye-open"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= form_for(@watch, remote: true, html: { class: "navbar-form navbar-right no-marg", role: "add stock to watchlist" }) do |f| %>
                    <div id="spy-list" class="form-group">
                      <%= f.text_field :ticker, placeholder: "Ticker, Symbol", class: "form-control", autocomplete: "off" %>
                      <%= f.submit "Spy", class: "btn btn-success form-control" %>
                    </div>
                  <% end %>
                </li>
                <li role="separator" class="divider"></li>
                <li class="text-center"><h3><strong>Watchlist</strong></h3></li>
                <li>
                  <div class="table-responsive">
                    <table id="watchlist" class="table-borderless table-condensed table-hover text-center">
                      <tr class="h4">
                        <th><strong>Ticker</strong></th>
                        <th><strong>Price</strong></th>
                        <th><strong>Change</strong></th>
                        <th><%= link_to("", watchlists_path, id: "refresh-watch",
                                                    class: "navi-btn glyphicon glyphicon-refresh", remote: true) %>
                      </tr>
                      <% watchlist_data = stock_watchlist(@watchlist) %>
                      <% watchlist_data.each do |data| %>
                        <%= render '/watchlists/stock_watchlist', stock: data %>
                      <% end %>
                    </table>
                  </div>
                </li>
              </ul>
             </li>

             <!-- search bar -->
             <li class="dropdown">
              <a href="#" class="dropdown-toggle navi-btn" data-toggle="dropdown"
                                                      role="button" aria-haspopup="true" aria-expanded="false">
                                                      <span class="glyphicon glyphicon-search"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <div id="stock-search-form">
                    <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-search-form' do %>
                      <div class="input-group">
                        <%= text_field_tag :search, params[:search], placeholder: "Enter company ticker", class: 'form-control', id: 'stock_search', autocomplete: "off" %>
                        <span class="input-group-addon">
                            <%= button_tag("",type: :submit, class: "btn btn-sm glyphicon glyphicon-search") %>
                        </span>
                      </div>
                    <% end %>
                  </div>
                </li>
                <li id="search-results"></li>
              </ul>

             </li>

             <!-- login and logout homepage -->
            <% else %>
              <li> <%= link_to("Login", new_user_session_path, class: "reset-fnt") %> </li>
              <li> <%= link_to("Sign up", new_user_registration_path, class: "reset-fnt") %> </li>
            <% end %>
          </ul>

        </div><!-- /.navbar-collapse -->
     </div> <!-- column -->
   </div> <!-- row -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yeeld - Portfolio management made easy</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <!-- Bootstrap minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Bootstrap minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <!-- Google charts for Chart kick -->
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
</head>

<%= render "layouts/navigation" %>

<div class="navspacer"></div>

<body>
  <%= yield %>
</body>


<%= render "layouts/footer" %>

</html>